version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0
    restart: always
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - ./chroma_data:/chroma/.chroma/index
    ports:
      - "8001:8000"
