"""Add CASCADE to audio_event_logs.message_id

Revision ID: 350b1c2914e3
Revises: 394e1af86b6c
Create Date: 2025-07-22 19:14:26.195335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350b1c2914e3'
down_revision: Union[str, None] = '394e1af86b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audio_event_logs_message_id_fkey'), 'audio_event_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audio_event_logs', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_event_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audio_event_logs_message_id_fkey'), 'audio_event_logs', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
